const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function api(path,{method='GET',body,headers={}}={}){const r=await fetch(path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});if(!r.ok){let e={};try{e=await r.json()}catch{}throw new Error(e.error?.message||`${r.status} ${r.statusText}`)}return r.status===204?null:r.json()}
function windowQuery(){const to=new Date(),from=new Date(to.getTime()-7*86400000);return `from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`}
const caps=kind=>({responses:kind==='responses',embeddings:kind==='embeddings',tools:kind==='responses',structured_outputs:false,input_modalities:['text'],output_modalities:kind==='embeddings'?['embedding']:['text'],context_window:kind==='responses'?128000:null,max_output_tokens:kind==='responses'?16384:null,embedding_space_id:kind==='embeddings'?'bge-m3-dense-1024-v1':null,embedding_dimensions:kind==='embeddings'?[1024]:null,embedding_max_batch_inputs:kind==='embeddings'?32:null,embedding_max_input_tokens:kind==='embeddings'?8192:null});
let state={providers:[],deployments:[],tiers:[]};
function status(h){return h==='healthy'?['健康','ok']:h==='degraded'||h==='unknown'?['需关注','warn']:['不可用','bad']}
async function loadHome(){try{const [p,d,t,ready]=await Promise.all([api('/tier/admin/v1/providers'),api('/tier/admin/v1/deployments'),api('/tier/admin/v1/service-levels'),fetch('/readyz',{credentials:'same-origin'}).then(async r=>({ok:r.ok,...await r.json()}))]);state={providers:p.data,deployments:d.data,tiers:t.data};const health=state.deployments.filter(x=>x.health==='healthy').length;$('#stat-tier').textContent=state.tiers.length;$('#stat-backend').textContent=state.deployments.length;$('#stat-health').textContent=`${health} / ${state.deployments.length-health}`;$('#stat-gateway').textContent=ready.status==='ready'?'正常':ready.status==='degraded'?'降级':'未就绪';$('#gateway').className=`pill ${ready.status==='ready'?'ok':'warn'}`;$('#gateway').textContent=`● ${$('#stat-gateway').textContent}`;renderTree();$('#stamp').textContent=`最后刷新 ${new Date().toLocaleTimeString()}`;$('#tier-select').innerHTML=state.tiers.map(x=>`<option>${x.id}</option>`).join('')}catch(e){$('#tree').textContent=e.message;$('#gateway').textContent='● 连接失败';$('#gateway').className='pill bad'}}
function renderTree(){const q=$('#search').value.toLowerCase();const provider=id=>state.providers.find(x=>x.id===id);$('#tree').className='tree';$('#tree').innerHTML=state.tiers.filter(t=>{const ds=t.deployment_ids.map(id=>state.deployments.find(x=>x.id===id)).filter(Boolean);return !q||t.id.toLowerCase().includes(q)||ds.some(d=>`${d.name} ${d.backend_model} ${provider(d.provider_id)?.name||''}`.toLowerCase().includes(q))}).map(t=>{const ds=t.deployment_ids.map(id=>state.deployments.find(x=>x.id===id)).filter(Boolean), overall=ds.some(d=>d.health==='healthy')?['可用','ok']:ds.length?['需关注','warn']:['不可用','bad'];return `<details open><summary><span class="tiername"><b>${t.id}</b><div class="subline">${ds.length} 个后端</div></span><span><i class="pill ${overall[1]}">${overall[0]}</i></span><span>${t.capabilities.responses?'Responses':'Embeddings'}</span><span>v${t.version}</span></summary>${ds.map(d=>{const p=provider(d.provider_id),s=status(d.health);return `<div class="backend"><span>└ <b>${p?.name||'未知供应商'}</b><div class="subline">${d.backend_model}</div></span><span><i class="pill ${s[1]}">${s[0]}</i></span><span>${p?.kind==='cloud'?'云供应商':'本地模型'}</span><span>v${d.version}</span></div>`}).join('')}</details>`}).join('')||'<div class="empty">没有匹配项</div>'}
async function loadUsage(){const p=await api('/tier/admin/v1/usage?'+windowQuery());$('#usage-body').innerHTML=p.data.map(x=>`<tr><td>${x.request_id}</td><td>${x.model}</td><td>${x.endpoint}</td><td>${x.input_tokens??'未知'}</td><td>${x.output_tokens??'未知'}</td><td>${x.total_tokens??'未知'}</td><td><i class="pill ${x.measurement_status==='measured'?'ok':'warn'}">${x.measurement_status}</i></td></tr>`).join('')||'<tr><td colspan="7">暂无记录</td></tr>'}
async function loadAudit(){const p=await api('/tier/admin/v1/audit');$('#audit-body').innerHTML=p.data.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString()}</td><td>${x.actor}</td><td>${x.action}</td><td>${x.target}</td><td>${x.result}</td></tr>`).join('')||'<tr><td colspan="5">暂无记录</td></tr>'}
async function loadLogs(){const q=new URLSearchParams(windowQuery());if($('#log-level').value)q.set('level',$('#log-level').value);if($('#log-module').value)q.set('module',$('#log-module').value);const p=await api('/tier/admin/v1/logs?'+q);$('#log-body').innerHTML=p.data.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString()}</td><td>${x.level}</td><td>${x.module}</td><td>${x.event}</td><td>${x.message}</td><td>${x.request_id||'—'}</td></tr>`).join('')||'<tr><td colspan="6">暂无记录</td></tr>'}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.page).classList.add('active');const m={home:['主页','一页查看全部模型、Tier 与后端状态'],records:['用量与审计','统一查看 Token 用量与管理变更'],logs:['日志','查看已脱敏的网关运行事件']}[b.dataset.page];$('#title').textContent=m[0];$('#subtitle').textContent=m[1];if(b.dataset.page==='records')loadUsage();if(b.dataset.page==='logs')loadLogs()});
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.sub').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active');b.dataset.tab==='audit'?loadAudit():loadUsage()});
$('#refresh').onclick=loadHome;$('#search').oninput=renderTree;$('#refresh-usage').onclick=loadUsage;$('#refresh-audit').onclick=loadAudit;$('#refresh-logs').onclick=loadLogs;$('#add').onclick=()=>$('#drawer-mask').classList.add('open');$('#close').onclick=$('#cancel').onclick=()=>$('#drawer-mask').classList.remove('open');
$('#model-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));$('#form-error').textContent='';try{const provider=await api('/tier/admin/v1/providers',{method:'POST',body:{name:f.provider_name,kind:f.kind,endpoint:f.endpoint,secret_ref:f.secret_ref||null,enabled:true}});const deployment=await api('/tier/admin/v1/deployments',{method:'POST',body:{name:f.deployment_name,provider_id:provider.id,backend_model:f.backend_model,capabilities:caps(f.capability),enabled:true}});const tier=state.tiers.find(x=>x.id===f.tier);await api(`/tier/admin/v1/service-levels/${encodeURIComponent(f.tier)}`,{method:'PATCH',headers:{'If-Match':`"${tier.id}.v${tier.version}"`},body:{deployment_ids:[...tier.deployment_ids,deployment.id]}});$('#drawer-mask').classList.remove('open');e.target.reset();await loadHome()}catch(err){$('#form-error').textContent=err.message}};
loadHome();
